// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVu9TGprO12rsS529VEXwDV2l0nHnPLF4',
    appId: '1:23968426916:web:440611ddb1b4746b8aef31',
    messagingSenderId: '23968426916',
    projectId: 'flutter-notes-1',
    authDomain: 'flutter-notes-1.firebaseapp.com',
    storageBucket: 'flutter-notes-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNlHWKnW56wX3aZMjdcJGjI7h9K2CloQ',
    appId: '1:23968426916:android:c6fffa752ea65c428aef31',
    messagingSenderId: '23968426916',
    projectId: 'flutter-notes-1',
    storageBucket: 'flutter-notes-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVgJdTYmFuPW-mkyle8CFP4yE-NqIyjM',
    appId: '1:23968426916:ios:2a2875022bade5af8aef31',
    messagingSenderId: '23968426916',
    projectId: 'flutter-notes-1',
    storageBucket: 'flutter-notes-1.appspot.com',
    iosClientId: '23968426916-fkfb572fmtnurm27jh95nvri2bg9g9vj.apps.googleusercontent.com',
    iosBundleId: 'com.wo1f.firstDartProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVgJdTYmFuPW-mkyle8CFP4yE-NqIyjM',
    appId: '1:23968426916:ios:2a2875022bade5af8aef31',
    messagingSenderId: '23968426916',
    projectId: 'flutter-notes-1',
    storageBucket: 'flutter-notes-1.appspot.com',
    iosClientId: '23968426916-fkfb572fmtnurm27jh95nvri2bg9g9vj.apps.googleusercontent.com',
    iosBundleId: 'com.wo1f.firstDartProject',
  );
}
